ds_parameters:
  path: "data_torch"
  shape: [4,5]
  n_data: 500
  split: 0.5
  batch_size: 16
  norm_x: "id"
  norm_y: "id"
  device: "cpu"
  # tf_args_x:
  # tf_args_y:
optim_parameters:
  lr: 0.0001
  weight_decay: 0.0001
learner_parameters:
  n_epochs_max: 300
  init_xavier: True
  l1_penalty: 1
  lr_reduce_epochs: 10
model_parameters:
  n_terms: "edges"
  geometry_parameters:
    shape: [4, 5]
    pauli_qubits: null
    delta1: 0
  local_parameters:
    width: 20
    depth: 2
    act_fun: "tanh"
path_model: "ml_torch/runs"
lognames: 
  best_model_file: "model_best.pkl"
  
