ds_parameters:
  batch_size: 16
  device: cuda:0
  n_data: 500
  norm_x: unit
  norm_y: id
  path: data_torch
  seq: rand
  shadow_size: 500
  shape:
  - 4
  - 5
  split: 0.3
  validation_split: 1
  y_indices: edges
learner_parameters:
  init_xavier: true
  l1_penalty: 2
  lr_reduce_epochs: 5
  n_epochs_max: 300
lognames:
  best_model_file: model_best.pkl
model_parameters:
  geometry_parameters:
    delta1: 1
    pauli_qubits: null
    shape:
    - 4
    - 5
  local_parameters:
    act_fun: tanh
    depth: 4
    dropout: 0
    width: 200
  n_terms: edges
optim_parameters:
  lr: 0.0005
  weight_decay: 1
path_eval: results
path_model: ml_torch/runs
